### ISSUE TITLE
Add search screen

### ISSUE THREAD

**Issue by wataru-maeda** [wataru-maeda/tourism-app#1]
# Todo

- [x] Add [map](https://github.com/react-community/react-native-maps)
  - [x] Add marker on the map
  - [x] Customize marker
- [x] Add place type selector with [caroucel style](https://github.com/archriss/react-native-snap-carousel)
  - [x] List up all place types used in google map and choose which types we use or not (Google spreadsheet prefered to list)
  - [x] Collect place type icons (flat one)
  - [x] Create place type component to use in the carousel
- [x] Hookup place api
  - [x] present venue in the list format
  - [x] change venue item contents
  - [x] fetch venue based on location, place type
  - [x] update venues after switched place type
