### ISSUE TITLE
Add side menu

### ISSUE THREAD

**Issue by wataru-maeda** [wataru-maeda/tourism-app#2]
# Todo
- [x] Add side meu
- [ ] list side menu item (Google Spreadsheet preferred)
  - [ ] customize place type
