### ISSUE TITLE
Add spot detail screen

### ISSUE THREAD

**Issue by wataru-maeda** [wataru-maeda/tourism-app#5]
place detail apis ([doc](https://developers.google.com/places/web-service/details))

# Todo

- [x] create mock screen
- [x] hookup place api
- [x] listup the contents to present
- [x] fetch 3 related images to show as header image
- [x] parse json response and present the listed data
- [ ] get icons for basic info field
- [ ] add besic info field
- [ ] style sections and each item

**Comment by WataruMaeda** [comment]
## response

- **All**

![screen shot 2018-11-14 at 10 46 09 pm](https://user-images.githubusercontent.com/14352132/48535225-6347ff00-e85f-11e8-899d-0c7c7c41ebd9.png)

- **photos**

![screen shot 2018-11-14 at 10 46 43 pm](https://user-images.githubusercontent.com/14352132/48535224-6347ff00-e85f-11e8-9db4-9a428d775d74.png)

- **rewiews**

![screen shot 2018-11-14 at 10 47 16 pm](https://user-images.githubusercontent.com/14352132/48535226-6347ff00-e85f-11e8-91b8-c41c75da405f.png)

**Comment by wataru-maeda** [comment]
# Items to present

formatted_address,
formatted_phone_number,
geometry,
id,
name,
opening_hours,
weekday_text,
photos,
place_id,
price_level,
rating,
reference,
reviews,
url,
utc_offset,
vicinity,
website,
